### ISSUE TITLE
リソース設計を行う

### ISSUE THREAD

**Issue by Kassy0220** [Kassy0220/fjord-minutes#27]
#5 に基づき、このIssueではリソース設計を行います。

- [エレベーターピッチ](https://bootcamp.fjord.jp/products/17398)
- [ペーパープロトタイプ](https://bootcamp.fjord.jp/products/19216)

アプリ内でアクセスできるページと、React内からデータを取得・更新するためのAPIを分けています。
## アクセス可能なリソース

| HTTPメソッド | パス                                | 説明                                                     | 
| ------------ | ----------------------------------- | -------------------------------------------------------- | 
| GET          | /                                   | アプリのトップページ(ログイン後はマイページが表示される) | 
| POST         | /auth/github             | GitHub OAth Appに認可リクエストを送る               | 
| GET          | /auth/:provider/callback | GitHub OAth Appから受け取った情報を元にログインする | 
| DELETE       | /logout                  | ログアウトする                                      | 
| GET         | /minutes    | 議事録一覧                     | 
| GET          | /minutes/:id                        | 議事録詳細                                               | 
| GET          | /minutes/:id/edit                   | 議事録編集                                               | 
| POST         | /minutes/:minute_id/exports         | 議事録をGitHub Wikiにエクスポートする                    | 
| GET          | /minutes/:minute_id/attendances/new | 議事録に紐づく出席を新規作成                             | 
| POST         | /minutes/:minute_id/attendances     | 議事録に紐づく出席作成                                   | 
| GET          | /attendances/:id/edit               | 出席編集                                                 | 
| PTACH        | /attendances/:id                    | 出席更新                                                 | 
| GET         | /members    | メンバー一覧                       | 
| GET          | /members/:id                        | チームメンバー詳細                                       | 
| GET          | /terms_of_service                   | 利用規約を表示                                           | 
| GET          | /privacy_policy                     | プライバシーポリシーを表示                               | 

備考
- ログインは、Devise + omniauthを使ってログインを行います
- 議事録の作成は、Rakeタスク + Heroku Scheduler で行います
- 議事録の更新は、議事録の各項目ごとにReactでフォームを作成しfetch APIを利用して行います

## API

| HTTPメソッド | パス                                | 説明                                             | 
| ------------ | ----------------------------------- | ------------------------------------------------ | 
| GET          | /api/minutes/:id                    | 議事録詳細                                       | 
| PATCH        | /api/minutes/:id                    | 議事録更新                                       | 
| GET          | /api/minutes/:minute_id/attendances | 議事録に紐づく出席一覧                         | 
| GET          | /api/minutes/:minute_id/topics      | 議事録に紐づく「話題にしたいこと・心配事」一覧 | 
| POST         | /api/minutes/:minute_id/topics      | 議事録に紐づく「話題にしたいこと・心配事」作成 | 
| PATCH        | /api/minutes/:minute_id/topics      | 議事録に紐づく「話題にしたいこと・心配事」更新 | 
| GET          | /api/members/:member_id/attendances | メンバーに紐づく出席一覧                       | 
| POST         | /api/members/:member_id/hiatuses    | メンバーに紐づく休止作成                       | 
| GET         | /api/minutes    | 議事録一覧                     | 
| GET         | /api/members    | メンバー一覧                       | 
 
備考
- 「 議事録詳細 」から「議事録に紐づく「話題にしたいこと・心配事」更新」までのAPIは、議事録編集ページ内の各項目を表示するReactコンポーネントからアクセスします
- 「メンバーに紐づく出席一覧」APIは、メンバー一覧やメンバー詳細でメンバーの出席状況を表示するReactコンポーネントからアクセスします
- 「メンバーに紐づく休止作成」APIは、メンバー一覧ページの`退会させる`ボタン(Reactコンポーネント)からアクセスします
- 「議事録一覧」APIは、議事録一覧ページで議事録一覧を表示するReactコンポーネントからアクセスします
- 「メンバー一覧」APIは、メンバー一覧ページでメンバー一覧を表示するReactコンポーネントからアクセスします

**Comment by maedana** [comment]
apiはURLに`v1`のようなバージョンを入れるというのをよくやりますね。将来互換性のない変更が必要になったときに`v2`を作ることで一定機関は`v1`と平行運用するようなケースを想定する感じです。今回そこまでしなくてもいいとは思いますがご参考までに。

**Comment by Kassy0220** [comment]
maedanaさん、コメントありがとうございます！

> apiはURLにv1のようなバージョンを入れるというのをよくやりますね。将来互換性のない変更が必要になったときにv2を作ることで一定機関はv1と平行運用するようなケースを想定する感じです。

URLに`v1`が含まれているコードを見たことがあって疑問に思っていたのですが、互換性のために追加しているのですね。
勉強になりました、ありがとうございます🙏

**Comment by Kassy0220** [comment]
リソース設計をご確認いただいたので、このIssueをクローズします。

**Comment by Kassy0220** [comment]
📝
先日町田さんとお話しした際、議事録一覧とメンバー一覧でコースの切り替えをReactで実装しようと考えていると伝えたところ、サービスの根幹と関わるところではないため、ページ遷移する形でも大丈夫だとアドバイスをいただきました。

そこで、議事録一覧とメンバー一覧ではコースのタブをクリックすると`/courses/:course_id/minutes`(または`/courses/:course_id/members`)にページ遷移するように仕様を変更することにしました。
仕様変更に伴いリソース設計を修正しています。

**Comment by Kassy0220** [comment]
#156 に関連して、ユーザーの休止処理を非同期からページ遷移する形で実装することに変更しました。
そこで、以下のリソース変更を行なっています。
- 削除したリソース : `/api/members/:member_id/hiatuses`
- 追加したリソース : `/members/:member_id/hibernations`
